language: php

php:
  - 7.1
  - 7.2
  
# This triggers builds to run on the new TravisCI infrastructure.
# See: https://docs.travis-ci.com/user/getting-started/#Selecting-infrastructure-(optional)
sudo: false

# Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - cd $TRAVIS_BUILD_DIR

script:
#  - composer check-style
  - composer phpstan
  - composer test-coverage
